In [1]:
## Steps to perform ##
#1. Prepare dataset 
#2. Class structure
#3. Gini Coeffienct
#4. Feature selector

In [8]:
import numpy as np

In [118]:
class TreeNode:
    def __init__(self, left = None, right = None, val = None, max_vote = None, is_leaf = False):
        self.left = left
        self.right = right
        self.val = val
        self.max_vote = max_vote
        self.is_leaf = is_leaf

class DecisionTree:
    def __init__(self):
        self.max_depth = 5
        self.root = None
        
    def entropy(self, vec):
        # numpy vector input
        prop1 = sum(vec == 1)/len(vec)
        prop0 = sum(vec ==0 )/len(vec)
        epsilon = 1e-5
        entropy = -prop1*np.log2(prop1+epsilon) - prop0*np.log2(prop0+epsilon)
        return entropy
    
    def feature_selector(self, X,y):
        max_ig = -float("inf"); chosen_feature_index = -1
        for feature_index in range(num_features):
            cutoff = np.median(X[:,feature_index])
            sliced = np.hstack([X[:,feature_index].reshape(-1,1), y.reshape(-1,1)])
            part1 = sliced[sliced[:,0] > cutoff][:,-1]
            part2 = sliced[sliced[:,0] <= cutoff][:,-1]
            # # 
            parent_entropy = self.entropy(y)
            post_split_entropy = (self.entropy(part1)*len(part1) + self.entropy(part2)*len(part2) )/len(y)
            information_gain = parent_entropy - post_split_entropy
            if information_gain > max_ig:
                max_ig = information_gain
                chosen_feature_index = feature_index

        return chosen_feature_index, max_ig,cutoff



    # Traininig function

    def __build(self, X, y, depth):
        max_vote = sum(y == 1) > sum(y ==0)
        
        if depth >= self.max_depth or len(y) == sum(y==1) or len(y) == sum(y==0):
            return TreeNode(is_leaf = True, max_vote = max_vote )
        chosen_feature_index, max_ig,cutoff = self.feature_selector(X,y)
        combined_data = np.hstack([X, y.reshape(-1,1)])
        left_data = combined_data[combined_data[:,chosen_feature_index] < cutoff]
        right_data = combined_data[combined_data[:,chosen_feature_index] > cutoff]
        
        if len(left_data) == 0 or len(right_data) ==0:
            return TreeNode(is_leaf = True, max_vote = max_vote )
        
        root = TreeNode()
        root.val = (chosen_feature_index , cutoff)
        root.left = self.__build(left_data[:, :-1], left_data[:,-1], depth+1)
        root.right = self.__build(right_data[:, :-1], right_data[:,-1],depth+1)
        root.max_vote = max_vote
        return root

    def train(self, X,y):
        depth = 0
        self.root = self.__build(X,y, depth)
    
    def predict(self, x_test, curr = None):
        if curr is None: curr = self.root # Starting point
            
        if curr.left is None and curr.right is None: # Its a leaf node
            return curr.max_vote
            
        feat_index , cutoff = curr.val
        if x_test[feat_index] > cutoff:
            return self.predict(x_test, curr.right)
        else:
            return self.predict(x_test, curr.left)
    

In [119]:
X = np.random.rand(100,4)*50 +4
y = np.random.choice([1,0], 100)  

model = DecisionTree()

In [120]:
model.train(X,y)

In [124]:
sum([model.predict(X[i], model.root) for i in range(100)])

81

In [122]:
y[:20]

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [80]:
  X[0]

array([ 5.71402344, 20.50145181,  9.43685723, 14.55038598])

In [30]:
nrows, num_features = X.shape

True

In [43]:
part1 =sliced[sliced[:,0] > 40]
part1

array([[40.44844233,  0.        ],
       [41.22510769,  1.        ],
       [52.25543081,  1.        ]])

In [47]:
cd = np.hstack([X, y.reshape(-1,1)])
cd

array([[52.82041225, 28.92661965, 53.73803466, 37.24061762,  1.        ],
       [46.24673417, 11.79848212, 45.62927583, 39.47683985,  0.        ],
       [20.26642427, 38.38630271,  4.31383442, 40.44844233,  0.        ],
       [ 8.75515664, 40.48673538,  8.91727415, 41.22510769,  1.        ],
       [38.56009015, 33.59446147, 32.16816286, 38.27464789,  0.        ],
       [13.08354242, 14.51476269, 23.16365033, 28.59021777,  1.        ],
       [45.81414391, 26.86294597, 26.33283119, 14.46110413,  0.        ],
       [23.26021692, 30.01265898, 13.15229917, 34.76174049,  1.        ],
       [32.28264403, 29.43658042, 44.11845513, 52.25543081,  1.        ],
       [ 5.50703255, 18.81331565, 33.56246253, 28.82128346,  1.        ]])

In [48]:
cd[cd[:,2] > 40]

array([[52.82041225, 28.92661965, 53.73803466, 37.24061762,  1.        ],
       [46.24673417, 11.79848212, 45.62927583, 39.47683985,  0.        ],
       [32.28264403, 29.43658042, 44.11845513, 52.25543081,  1.        ]])