In [2]:
# To DO

# Forward propagation
# Backward Propagation

In [ ]:
import numpy as np

In [4]:
class NeuralNetwork:
    def __init__(self, num_inputs = None, num_classes = None, hidden_layer_size = []):
        self.num_rows = None
        self.num_inputs = num_inputs
        self.num_classes = num_classes
        self.hidden_layer_size = hidden_layer_size
        self.epochs = 10
        self.weights = []
        self.intermediate_data = []
        
    def sigmoid(self,z):
        return 1.0/(1+np.exp(-z))
    
    def softmax(self, z):
        tot = np.sum(np.exp(z))
        return np.exp(z)/tot
    
    def ce_loss(self, y, y_pred):
        #loss = 0
        #for i in range(len(y)):
        #    loss += -1*np.log(y_pred[i,y_pred[i]])
        #return loss/len(y)
    
        return -np.sum(np.log2(y_pred[range(len(y)), y]))
        
    def weights_initialize(self):
        temp = [self.num_inputs] + self.hidden_layer_size + [self.num_classes]
        for h in range(len(temp) - 1):
            W = np.random.rand(temp[h], temp[h+1])
            self.weights.append(W)
        
    def forward(self, X):
        a = X
        for h in range(len(self.hidden_layer_size)):
            z = np.matmul(a, self.weights[h])
            a = self.sigmoid(z)
            self.intermediate_data.append([z,a])
            
        # last layer
        z = np.matmul(a, self.weights[h+1])
        y_prob = self.softmax(z)
        self.intermediate_data.append([z,y_prob])
        return y_prob
    
    def backward(self, X, y):
        # Compute gradients = []
        # compute self.weights
        y_modified = np.zeros((self.num_rows,self.num_classes))
        pp[range(10), y] = 1

        z,a = self.intermediate_data[-1]
        dz = a - y_modified
        z_prev, a_prev =  self.intermediate_data[-2]
        dw = np.matmul(a_prev.T, dz)/self.num_rows
        da_prev = np.matmul(dz, w) 
        
    
    def train(self, X_no_bias, y):
        ones = np.ones((X_no_bias.shape[0], 1))
        X = np.hstack([ones, X_no_bias])
        nrows, nfeats = X.shape
        self.num_inputs = nfeats
        self.num_rows = nrows
        self.num_classes= len(set(y))
        
        self.weights_initialize() # Initialize weights
        losses = []
        for epoch in self.epochs:
            y_prob = self.forward(X)
            losses.append(self.ce_loss(y, y_prob))
            self.backward(X,y)
        print (losses)
        
    def predict(self, X_test):
        y_prob = self.forward(X_test)
        return np.argmax(y_prob, axis = 1)
        

In [17]:
y = np.random.choice([0,1,2], 10)
y

array([2, 0, 0, 1, 1, 2, 0, 1, 0, 0])

In [15]:
data  = np.random.rand(10,3)
data

array([[0.37913545, 0.52119838, 0.32227038],
       [0.99608508, 0.83016664, 0.54925934],
       [0.83906725, 0.31229312, 0.53653331],
       [0.34271652, 0.21526398, 0.0385661 ],
       [0.28806022, 0.92618904, 0.46235222],
       [0.3464293 , 0.95879138, 0.68625296],
       [0.76036639, 0.79776297, 0.04684361],
       [0.58748243, 0.03348148, 0.02548151],
       [0.75876664, 0.83657795, 0.69261966],
       [0.99217496, 0.98954445, 0.32103255]])

In [38]:
y

array([2, 0, 0, 1, 1, 2, 0, 1, 0, 0])

In [35]:
data

array([[0.37913545, 0.52119838, 0.32227038],
       [0.99608508, 0.83016664, 0.54925934],
       [0.83906725, 0.31229312, 0.53653331],
       [0.34271652, 0.21526398, 0.0385661 ],
       [0.28806022, 0.92618904, 0.46235222],
       [0.3464293 , 0.95879138, 0.68625296],
       [0.76036639, 0.79776297, 0.04684361],
       [0.58748243, 0.03348148, 0.02548151],
       [0.75876664, 0.83657795, 0.69261966],
       [0.99217496, 0.98954445, 0.32103255]])

In [43]:
data[range(11), y] -= 1

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (11,) (10,) 

In [42]:
data

array([[ 0.37913545,  0.52119838, -0.67772962],
       [-0.00391492,  0.83016664,  0.54925934],
       [-0.16093275,  0.31229312,  0.53653331],
       [ 0.34271652, -0.78473602,  0.0385661 ],
       [ 0.28806022, -0.07381096,  0.46235222],
       [ 0.3464293 ,  0.95879138, -0.31374704],
       [-0.23963361,  0.79776297,  0.04684361],
       [ 0.58748243, -0.96651852,  0.02548151],
       [-0.24123336,  0.83657795,  0.69261966],
       [-0.00782504,  0.98954445,  0.32103255]])